### ISSUE TITLE
App fails to start with gradio 6 (allowed by `gradio>=5.49.1`)

### ISSUE THREAD

**Issue by OrcVole** [speaches-ai/speaches#678]
`pyproject.toml` pins `gradio>=5.49.1` with no upper bound, so any re-resolve of the lock (for example to pick up gradio's security fixes, which only exist in 6.x) installs gradio 6, and speaches then breaks in two places (seen on v0.9.0-rc.3, commit 24f209c9, gradio 6.15.1):

1. **The app does not start.** `src/speaches/ui/tabs/audio_chat.py` passes `type="messages"` to `gr.ChatInterface`, which gradio 6 removed:

   ```
   ERROR: Error loading ASGI app factory: ChatInterface.__init__() got an unexpected keyword argument 'type'
   ```

   Because the UI is built in the app factory, this takes down the whole API, not just the playground.

2. **The playground's API key helpers disappear silently.** gradio 6 moved `head` from `gr.Blocks()` to `launch()`/`mount_gradio_app()`, and `mount_gradio_app` overwrites `blocks.head` with its own (empty) argument. The `<script>` defining `loadApiKey`/`saveApiKey` is never sent, so the API key field stops working, while the page still loads without an error.

**Minimal fix** (works on gradio 6.15.1; TTS, STT and the UI all tested):

```diff
# src/speaches/ui/tabs/audio_chat.py
         gr.ChatInterface(
-            type="messages",
             multimodal=True,

# src/speaches/main.py
-        app = gr.mount_gradio_app(app, create_gradio_demo(config), path="")
+        demo = create_gradio_demo(config)
+        app = gr.mount_gradio_app(app, demo, path="", head=demo._deprecated_head)
```

(A cleaner version of the second change passes the head string to `mount_gradio_app` directly instead of reading the private attribute.) Otherwise, capping `gradio<6` would stop the crash, but it also holds back gradio's security fixes and, through gradio 5's own caps, pillow < 12 and starlette < 1.0.
